dubbo:
  cloud:
    subscribed-services: user-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
    check: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knife?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-test-query: select 1
oauth:
  client:
    security:
      ignore:
        urls:
          - /oauth/**
          - /actuator/health

logging:
  level:
    root: info
    com:
      alibaba:
        nacos:
          naming:
            log:
              level: warn
          client:
            config: warn